# Generated by Django 5.2.8 on 2025-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Forma_Pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTÃO', 'Cartao')], default='PIX', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='Q_Estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('MODULOS', 'Módulos'), ('INVERSORES', 'Inversores'), ('COMPONENTES_ELETRONICOS', 'Componentes Eletrônicos'), ('ESTRUTURAS_GALVANIZADAS', 'Estruturas Galvanizadas'), ('PARAFUSOS', 'Parafusos'), ('CABOS', 'Cabos'), ('BATERIAS', 'Baterias')], default='MODULOS', max_length=30),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Descrição do produto será adicionada aqui.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Novo Produto', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
